In [7]:
import pandas as pd
import numpy as np

data = {
    'Student_ID': [101, 102 , 103, 104, 105, 105,106],
    'Name': ['Alice ', 'bob', 'Charlie', 'Daisy', 'Ethan', 'Ethan', 'Frank'], # Typos/spaces
    'Subject': ['Math', 'Science', 'Math', 'History', 'Science', 'Science', 'UNKNOWN'], # Missing value string
    'Score': [85.0, np.nan, 92.0, -10.0, 45.0, 45.0, 88.0], # NaN and an impossible negative score
    'Passed': ['True', 'False', 'TRUE', 'True', 'False', 'False', 'UNKNOWN'] # Inconsistent text
}

df_data = pd.DataFrame(data)
df_data

   Student_ID     Name  Subject  Score   Passed
0         101   Alice      Math   85.0     True
1         102      bob  Science    NaN    False
2         103  Charlie     Math   92.0     TRUE
3         104    Daisy  History  -10.0     True
4         105    Ethan  Science   45.0    False
5         105    Ethan  Science   45.0    False
6         106    Frank  UNKNOWN   88.0  UNKNOWN

In [8]:
#removing duplicates
df_data = df_data.drop_duplicates()

In [9]:
#cleaning string
df_data['Name'] = df_data['Name'].str.strip().str.capitalize()

In [10]:
#fixing outliers
df_data.loc[df_data['Score'] < 0, 'Score'] = np.nan

In [11]:
#handling missing values
mean_score = df_data['Score'].mean()
df_data['Score'] = df_data['Score'].fillna(mean_score)

In [12]:
#standardizing text values
df_data['Passed'] = df_data['Passed'].astype(str).str.upper()
df_data['Passed'] = df_data['Passed'].replace('UNKNOWN', 'FALSE')

In [13]:
#replace specific text errors
df_data['Subject'] = df_data['Subject'].astype(str).str.upper()
df_data['Subject'] = df_data['Subject'].replace('UNKNOWN', 'ENGLISH')

In [14]:
median_value = df_data['Student_ID'].median()
#filling the missing cells with that median
df_data['Student_ID'] = df_data['Student_ID'].fillna(median_value)

In [15]:
df_data

   Student_ID     Name  Subject  Score Passed
0         101    Alice     MATH   85.0   TRUE
1         102      Bob  SCIENCE   77.5  FALSE
2         103  Charlie     MATH   92.0   TRUE
3         104    Daisy  HISTORY   77.5   TRUE
4         105    Ethan  SCIENCE   45.0  FALSE
6         106    Frank  ENGLISH   88.0  FALSE

In [16]:
exam_data = {
    'hours_studied': [8, 1.3, 4, 3.5, 9.1, 8.4],
    'sleep_hours': [8.8, 8.6, 8.2, 4.8, 6.4, 5.1],
    'attendance_percent': [72.1, 60.7, 73.7, 95.1, 89.8, 58.2],
    'previous_scores': [45, 55, 86, 66, 71, 75],
    'exam_score': [30.2, 25.0, 35.8, 34.0, 40.3, 35.7]
}
df_exam = pd.DataFrame(exam_data)
df_exam

   hours_studied  sleep_hours  attendance_percent  previous_scores  exam_score
0            8.0          8.8                72.1               45        30.2
1            1.3          8.6                60.7               55        25.0
2            4.0          8.2                73.7               86        35.8
3            3.5          4.8                95.1               66        34.0
4            9.1          6.4                89.8               71        40.3
5            8.4          5.1                58.2               75        35.7

In [21]:
df_data = df_data.reset_index(drop=True)
df_exam = df_exam.reset_index(drop=True)

df = pd.concat([df_data, df_exam], axis=1)

In [20]:
df

,Student_ID,Name,Subject,Score,Passed,hours_studied,sleep_hours,attendance_percent,previous_scores,exam_score
0,101,Alice,MATH,85.0,TRUE,8.0,8.8,72.1,45,30.2
1,102,Bob,SCIENCE,77.5,FALSE,1.3,8.6,60.7,55,25.0
2,103,Charlie,MATH,92.0,TRUE,4.0,8.2,73.7,86,35.8
3,104,Daisy,HISTORY,77.5,TRUE,3.5,4.8,95.1,66,34.0
4,105,Ethan,SCIENCE,45.0,FALSE,9.1,6.4,89.8,71,40.3
5,106,Frank,ENGLISH,88.0,FALSE,8.4,5.1,58.2,75,35.7